### ISSUE TITLE
updater can not be used without http libary

### ISSUE THREAD

**Issue by bckmnn** [flaviotordini/updater#1]
Hi there, it seems like updater can not be used without your http library. 

downloader.cpp includes "http.h", which on my windows machine resolves to something from the windows sdk giving me a lot of compliation errors. Maybe you can add it to the readme.

**Comment by flaviotordini** [comment]
Thanks I'll fix it when I get back to a project using the lib. Or just submit a PR. Should be trivial. Search for `ifdef HTTP` in the code
