### ISSUE TITLE
Fatal error nmake

### ISSUE THREAD

**Issue by lorenko** [flaviotordini/updater#3]
Hi, compiling your project with msvc_2019x64 got these errors

`        cl -c -nologo -Zc:wchar_t -FS -Zc:rvalueCast -Zc:inline -Zc:strictStrings -Zc:throwingNew -permissive- -Zc:__cplusplus -Zc:externConstexpr -O2 -MD -std:c++17 -utf-8 -W3 -w34100 -w34189 -w44996 -w44456 -w44457 -w44458 -wd4577 -wd4467 -EHsc -DUNICODE -D_UNICODE -DWIN32 -D_ENABLE_EXTENDED_ALIGNED_STORAGE -DWIN64 -DUPDATER -DUPDATER_DEFAULT -DNDEBUG -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -D_WINDLL -I..\..\updater -I. -I..\src -I..\src\impl -ID:\Qt\6.4.0\msvc2019_64\include -ID:\Qt\6.4.0\msvc2019_64\include\QtWidgets -ID:\Qt\6.4.0\msvc2019_64\include\QtGui -ID:\Qt\6.4.0\msvc2019_64\include\QtNetwork -ID:\Qt\6.4.0\msvc2019_64\include\QtCore -Irelease -I/include -ID:\Qt\6.4.0\msvc2019_64\mkspecs\win32-msvc -Forelease\ @C:\Users\quadr\AppData\Local\Temp\nmB3A0.tmp
downloader.cpp
..\src\impl\downloader.cpp(50): error C2440: 'static_cast': impossibile convertire da 'QNetworkReply::NetworkError (__cdecl QNetworkReply::* )(void) const' a 'void (__cdecl QNetworkReply::* )(QNetworkReply::NetworkError)'
..\src\impl\downloader.cpp(50): note: I tipi a cui si punta sono privi di relazioni. La conversione richiede reinterpret_cast, cast di tipo C o cast di tipo funzione
..\src\impl\downloader.cpp(49): error C2664: 'QMetaObject::Connection QObject::connect(const QObject *,const char *,const char *,Qt::ConnectionType) const': impossibile convertire l'argomento 2 da 'updater::Downloader *' a 'const char *'
..\src\impl\downloader.cpp(52): note: I tipi a cui si punta sono privi di relazioni. La conversione richiede reinterpret_cast, cast di tipo C o cast di tipo funzione
D:\Qt\6.4.0\msvc2019_64\include\QtCore/qobject.h(436): note: vedere la dichiarazione di 'QObject::connect'
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\cl.EXE"' : codice restituito '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nmake.exe"' : codice restituito '0x2'
Stop.`

**Comment by flaviotordini** [comment]
Thanks fixed
